QUERY_CATEGORIAS = """SELECT id, nome, sigla, ativo FROM categorias WHERE ativo = TRUE"""
QUERY_CATEGORIA_ID = """SELECT id, nome, sigla, ativo FROM categorias where id = %s AND ativo = TRUE"""
QUERY_CREATE_CATEGORIA = """INSERT INTO categorias (nome, sigla) VALUES (%s, %s) RETURNING id"""
QUERY_PUT_CATEGORIA = "UPDATE categorias SET nome = (%s), sigla = (%s) WHERE categorias.id = (%s) RETURNING id, nome, sigla, ativo"
QUERY_DELETE_CATEGORIA = """UPDATE categorias SET ativo = FALSE WHERE categorias.id = (%s) RETURNING id, nome, sigla, ativo"""
